name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-2019
    
    env:
      DOCKER_IMG_TAG: davidlatwe:foo
      DOCKER_CONTAINER: container_foo

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --file foo/Dockerfile --tag ${env:DOCKER_IMG_TAG} foo

    - name: Run the Docker image
      run: docker run --name ${env:DOCKER_CONTAINER} --detach ${env:DOCKER_IMG_TAG}

    - name: Extract artifact from container
      run: docker cp ${env:DOCKER_CONTAINER}:C:/build ./build

    - name: Archiving artifact
      run: python -c "import shutil;shutil.make_archive('artifact', 'zip', 'build')"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: foo
        path: ./artifact.zip
