name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-2019
    
    env:
      DOCKER_IMG_TAG: davidlatwe:foo

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${env:DOCKER_IMG_TAG}

    - name: Run the Docker image
      run: docker run ${env:DOCKER_IMG_TAG}

    - name: Extract atrifact from container
      run: docker cp ${env:DOCKER_IMG_TAG}/foo.txt ./build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: foo
        path: ./build
