name: USD build script

on: [push]

env:
  PIXAR_USD_GIT_URL: https://github.com/PixarAnimationStudios/USD.git
  PIXAR_USD_GIT_TAG: v21.02

jobs:
  build:
    # For Visual Studio 2017
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MS Visual C++ dev-cmd-prompt
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    
    - name: Pull Pixar/USD
      run: git clone --depth 1 --branch ${env:PIXAR_USD_GIT_TAG} ${env:PIXAR_USD_GIT_URL}
    
    - name: Install Python dependency packages
      run: pip install pyside pyopengl jinja2

    - name: Install Choco dependency packages
      run: choco install nasm -y

    - run: echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Run build script
      run: python USD\build_scripts\build_usd.py ./install --build ./build --src ./downloads --dry_run

    - name: List build dir
      run: dir ./install

    - name: Archiving artifact
      run: python -c "import shutil;shutil.make_archive('artifact', 'zip', 'install')"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: USD
        path: ./artifact.zip
