name: USD build script

on: [push]

env:
  PIXAR_USD_GIT_URL: https://github.com/PixarAnimationStudios/USD.git
  PIXAR_USD_GIT_TAG: v21.02

jobs:
  build:
    # For Visual Studio 2017
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    
    - name: Pull Pixar/USD
      run: git clone --depth 1 --branch ${env:PIXAR_USD_GIT_TAG} ${env:PIXAR_USD_GIT_URL}

    - name: Setup MS Visual C++ dev-cmd-prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: python USD\build_scripts\build_usd.py ./build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: USD
        path: ./build
