name: USD build script

on: [push]

env:
  PIXAR_USD_GIT_URL: https://github.com/PixarAnimationStudios/USD.git
  PIXAR_USD_GIT_TAG: v21.02

jobs:
  build:
    # For Visual Studio 2017
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MS Visual C++ dev-cmd-prompt
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    
    - name: Pull Pixar/USD
      run: git clone --depth 1 --branch ${env:PIXAR_USD_GIT_TAG} ${env:PIXAR_USD_GIT_URL}
    
    - name: Install dependencies
      run: pip install pyside pyopengl jinja2

    - name: Build
      run: python USD\build_scripts\build_usd.py ./build

    - name: Archiving artifact
        run: python -c "import shutil;shutil.make_archive('artifact', 'zip', 'build')"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: USD
        path: ./artifact.zip
